### PR TITLE
Intel OpenVINO backend for deep learning

### PR DESCRIPTION
**Pull request by dkurt**
Proposed Intel OpenVINO backend for performance optimization of deep learning model.

WIP: try to minimize the changes and try to make it as smooth as possible for users.

- [ ] Asynchronouse inference for tiles
- [ ] Modify documentation
- [ ] Check with GUI
- [ ] Can we use higher tile resolution?

Measured efficiency (single forward pass):

| Hardware | TensorFlow | OpenVINO |
|---|---|---|
| Intel(R) Core(TM) i7-6700K | 1.29s | 0.95s (x1.35) |

### CODE REVIEW

**Comment by mstritt** [comment]
Dear @dkurt,
thanks a lot for submitting this PR, very nice work!
We'll have a look on it soon and come back to you.
Regards,
Manuel

**Comment by dkurt** [comment]
@mstritt, Many thanks for the feedback! I marked it as draft for now. Just wanted to finish some tasks before review and save your time.

**Comment by dkurt** [comment]
@mstritt, can you please guide how to run segmentation model using GUI? I've added a model by F3 -> Deep Learning Segmentation and uploaded an image. What should be done next?

**Comment by mstritt** [comment]
@dkurt , after that "set primary segmentation model" and "segmentation", then you should see the segmented objects.
See also this tutorial (for a standard segmentation): https://www.orbit.bio/help/object-segmentation/

**Comment by dkurt** [comment]
@mstritt, Seems to me that segmentation is not started by "Object Segmentation". Logs:
```
12:40:58.485 INFO  c.a.r.o.i.c.OrbitImageAnalysis:1085 - objectSegmentation called [method call]
12:40:58.486 INFO  c.a.r.o.i.c.OrbitImageAnalysis:1158 - reloadROI called [method call]
```
There is no processing thread in the system monitor or something like that.

**Comment by dkurt** [comment]
@mstritt, May I ask for help?

**Comment by mstritt** [comment]
@dkurt ,
not sure what exactly went wrong.
Could you please first give it a try with standard (non-deep learning) segmentation, like described here:
https://www.orbit.bio/help/object-segmentation/ .
Does that work (try it on a small image first) ?

If that works, then in the features "F3" switch to deep learning segmentation (and afterwards use the "AI object segmentation" button instead of the "object segmentation" button.

**Comment by dkurt** [comment]
Maybe I do something wrong but there is no segmentation on the image. After Train I pushed Classify (F8) button. After some processing time, it creates a window "Classifiation Result". Then I tried "Set Primary Segmentation Model" + "Object Segmentation". After some time, "Object Count" appeared. However there is no mask on the image.

image
image

**Comment by dkurt** [comment]
There is something wrong with full image processing (tried "Classify (F8)"). It works for ROI but not when do ROI->Reset to choose entire image.

<details>
<summary>on the ROI</summary>

image

</details>

<details>
<summary>on the Full image</summary>

image

</details>

**Comment by mstritt** [comment]
Dear @dkurt ,
might be a rendering issue. It only renders for some ms and then stops rendering to not slow down the system. Try to zoom in (so that only a part of the image is visible).
Also give it a try on a small image. 
However, the segmentations (yellow shapes) after object segmentation should be visible.
Anyhow,thanks a lot for trying and all your efforts!
Manuel

**Pull request closed without merging**
